### ISSUE TITLE
How to install this web app?

### ISSUE THREAD

**Issue by menuliskode** [parmanputu/world-wise-webapp#11]
I think you need to update readme file and add information about this web app and how to use it.

**Comment by hendramchen** [comment]
Hi menuliskode, this web app is using react by vite.
Actually you just need to run this command: `npm install`. Once it done, then run: `npm run dev`.
You can open package.json file to see script command.

**Comment by menuliskode** [comment]
Thanks for answering my question. I will close this issue.
